### ISSUE TITLE
General Restyling

### ISSUE THREAD

**Issue by suidpit** [pwnthemole/pwnthemole.github.io#8]
Our standard jekyll hacker theme has served us well, but I believe it's time to give our website something more functional and..juicy :)

Basically, we should choose another theme (or stick with the current one), overriding its functionalities to provide:

-  A proper way to handle posts, indexing them by author or tag (Jekyll collections might come in handy here)
-  Fix the current issues with image sizing, when embedded in posts
- Cookie bar for GDPR-compliance, as needed after #5. 
- UI improvements
- A serious 'About us' section :)

What do you think? Something more to add in the checklist here?

**Comment by MauroFoti** [comment]
I would surely remove the "join us" section for now

**Comment by suidpit** [comment]
Good call. Another thing could be a public calendar to open up to the public some robust talk.

**Comment by lpezzolla** [comment]
I'd start from a cleaner theme (i.e. [Thinkspace](https://heiswayi.github.io/thinkspace/)) and evolve from there once we get a well-defined a color palette from our logo
